### ISSUE TITLE
4. Görev 

### ISSUE THREAD

**Issue by iyazici00** [HuseyinAk/Konsol-deneme#1]
GetSentence(out int lettersize,out int wordsize)  metodunda aşağıdaki gösterimde lettersize=textlength

352 ve 353. satırlara bu yazılabilir.

    char bosluk = ' ';
    int sayac = 0;
            for (int i = 0; i < input.Length; i++)
            {
                if(input[i] == bosluk)
                {
                    sayac++;
                }
            }
       textlength = input.Length - sayac;

**Comment by HuseyinAk** [comment]
GetSentence metodu güncellendi.
